--- Exercise 1.6
--- Can you gather from the definition of divides
--- what the type declaraion for rem would look like?
---
--- The type declaration for rem looks like: 
--- rem :: Integer -> Integer -> Integer
