(define (make-point x y)
  (cons x y))
(define (x-point p)
  (car p))
(define (y-point p)
  (cdr p))
(define (make-segment x y)
  (cons x y))
(define (start-segment s)
  (car s))
(define (end-segment s)
  (cdr s))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define (midpoint-segment s)
  (make-point (/ (+ (x-point (start-segment s)) (x-point (end-segment s))) 2)
              (/ (+ (y-point (start-segment s)) (y-point (end-segment s))) 2)))

(define point-a (make-point 2 6))
(define point-b (make-point 6 2))
(define segment-a (make-segment point-a point-b))
(define midpoint-ab (midpoint-segment segment-a))

(print-point point-a)
(print-point point-b)
(print-point midpoint-ab)
